config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :update]
  resources :characters
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name, scope: :user

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  NULL_ATTRS = %w[impersonating].freeze

  validate :validate_username
  validate :validate_avatar
  validate :validate_cover_photo
  before_save :nil_if_blank

  has_one_attached :avatar
  has_one_attached :cover_photo
  has_many :characters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  attr_writer :login

  def login
    @login || username || email
  end
  # rubocop:disable Lint/AssignmentInCondition
  # rubocop:disable Layout/EmptyLineBetweenDefs
  # rubocop:disable Style/HashSyntax
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
  # rubocop:enable Style/HashSyntax
  # rubocop:enable Layout/EmptyLineBetweenDefs
  # rubocop:enable Lint/AssignmentInCondition

  # rubocop:disable Style/GuardClause
  def avatar_resize
    if avatar.attached?
      @resize = MiniMagick::Image.read(avatar.download)
      @resize = @resize.resize '200x200^'
      @filename = avatar.filename
      @content_type = avatar.content_type
      avatar.purge
      avatar.attach(io: File.open(@resize.path), filename: @filename, content_type: @content_type)
    end
  end
  # rubocop:enable Style/GuardClause

  protected

  def validate_avatar
    return errors.add(:avatar, :invalid) unless avatar.blob.content_type.starts_with?('image/')
  end

  def validate_cover_photo
    return errors.add(:cover_photo, :invalid) unless cover_photo.blob.content_type.starts_with?('image/')
  end

  def validate_username
    return errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit(:account_update, keys: [added_attrs, :impersonating])
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @user = User.find(current_user.id)
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = current_user.characters.new
  end

  def create
    @character = current_user.characters.build(character_params)
    if @character.save
      flash.notice = 'Character succesfully created'
      redirect_to characters_path
    else
      flash.alert = @character.errors.full_messages
      render :new
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update(character_params)
      flash.notice = 'Character succsesfully edited'
      redirect_to character_path(params[:id])
    else
      flash.alert = @character.errors.full_messages
      render :edit
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    flash.notice = 'Character deleted'
    redirect_to user_path(current_user)
  end

  private

  def character_params
    params.require(:character).permit(:name, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user == current_user and @user.update(impersonating_param)
      @user.avatar_resize
      render :show
    else
      flash.notice = @user.errors.full_messages
      redirect_to user_path(params[:id])
    end
  end

  private

  def impersonating_param
    params.require(:user).permit(:impersonating, :avatar, :cover_photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>
  Character Name:<br>
  <%= f.text_field :name %><br>
  Character Description:<br>
  <%= f.text_area :description %><br>
  <%= f.submit "Create Charachter" %>
<% end %>

app/views/characters/destroy.html.erb
<h1>Characters#destroy</h1>
<p>Find me in app/views/characters/destroy.html.erb</p>

app/views/characters/edit.html.erb
<%= render partial: 'form' %>

app/views/characters/index.html.erb
<h1><%= @user.username %>'s Charatcers</h1>
<%= link_to 'New Character', new_character_path %><br>
<%= link_to 'Profile', user_path(current_user) %><br>
<% @user.characters.each do |character| %>
  <%= link_to character.name, character_path(character.id) %><br>
<% end %>

app/views/characters/new.html.erb
<%= render partial: 'form' %>

app/views/characters/show.html.erb
<h2><%= @character.name %></h2>
<p><%= @character.description %></p>
<%= link_to "Edit character", edit_character_path(@character.id) %>
<%= link_to "Delete character", character_path(params[:id]), method: :delete, data: { confirm: 'Are you sure you want to delete this? This action can\'t be undone'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rolcharts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <h1><%= current_user.username %></h1>
  <%= link_to "Profile", user_path(current_user) %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <%= link_to "Edit", edit_user_registration_path %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path  %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>
<br>
<% User.all.each do |u| %>
  <%= link_to u.username, user_path(u.id) %><br>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @user.avatar.attached? %>
  <div style="border: 3px solid blue; width: 200px; height: 200px; overflow: hidden; border-radius: 50%;">
    <%= image_tag @user.avatar %>
  </div>
<% end %>
<% if @user.cover_photo.attached? %>
  <%= image_tag @user.cover_photo.variant(resize: '500x500') %>
<% end %>
<h1><%= @user.username %></h1>
<h2><%= @user.impersonating %></h2>
<%= link_to "Characters", characters_path %>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :cover_photo %>
    <%= f.file_field :cover_photo %>
  </div>

  <div>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div>
    <%= f.label 'Who am I today?' %><br>
    <%= f.select :impersonating, @user.characters.all.collect { |c| [c.name, c.name]  }, include_blank: @user.username %><br>
    <%= f.submit "Update Character" %>
  </div>
<% end %>